# Generated by Django 2.1.7 on 2019-07-21 02:16

from django.db import migrations, models
import django.db.models.deletion
import processo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divisao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_divisao', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=100)),
                ('protocolo_processo', models.CharField(max_length=100)),
                ('nome_parte_processo', models.CharField(max_length=100)),
                ('assunto_processo', models.CharField(max_length=250)),
                ('data_abertura_processo', models.DateField()),
                ('numero_caixa_processo', models.IntegerField(max_length=6)),
                ('arquivo_processo', models.FileField(default='sem_arquivo', upload_to=processo.models.user_directory_path)),
                ('criacao_registro', models.DateField(auto_now_add=True)),
                ('modificacao_registro', models.DateField(auto_now=True)),
                ('divisao_processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processo.Divisao')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeProcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tipo', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='processo',
            name='tipo_processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processo.TipoDeProcesso'),
        ),
    ]
