# Generated by Django 2.1.7 on 2019-07-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='numero_caixa_processo',
            field=models.IntegerField(),
        ),
    ]
